fragment CurrentOrderFields on Order {
  id
  number
  token
  userId
  total
  itemTotal
  itemCount
  shipAddress {
    id
    address {
      id
      firstName
      mobile
      address1
      address2
      addressAlias
    }
  }

  items {
    id
    price
    quantity
    variant {
      id
      images
      price
      sku
      product {
        id
        name
      }
    }
  }
}
