fragment MeUserAddressFields on User {
  id
  firstName
  lastName
  email
  mobile
  nickName
  createdAt
  updatedAt
  userAddresses {
    edges {
      node {
        ...UserAddressFields
      }
    }
  }
}
