fragment MeUserAddressFields on User {
  id
  firstName
  lastName
  email
  mobile
  nickName
  createdAt
  updatedAt
  userAddresses(sort: { field: "updatedAt", direction: desc }) {
    nodes {
      ...UserAddressFields
    }
  }
}
