fragment UserFields on User {
  id
  firstName
  lastName
  email
  mobile
  nickName
  createdAt
  updatedAt
  userAddresses {
    edges {
      node {
        address {
          address1
          address2
          addressAlias
          id
        }
      }
    }
  }
}
