schema: ./schema.graphql
extensions:
  endpoints:
    local:
      url: http://127.0.0.1:3201/graphql
      introspect: true
      headers:
        Authorization: Bearer eyJraWQiOiJ2aXJhc29mdCIsImFwcCI6MiwiYWxnIjoiUlMyNTYifQ.eyJpc3MiOiJWaXJhU29mdFN1cHBJc3N1ZXIiLCJpYXQiOjE3MzMyMDYzNzcsImV4cCI6MTc2NDc2MzMyOSwid2lkIjoyLCJpZHgiOiJ2aXJhc29mdCIsImp0aSI6IjcwNmQ2N2JkLWM2M2ItNGRkOC05MGNjLWIwNzlhNGFiMTQ5YyIsInNjb3BlcyI6InB1YmxpYyJ9.m9z69NuIakfk9dzYAoP_rF3-Xgj64KN0wMGkn1Dihfsx4DItIiNJlKCr2dlxh2lsLXSnuVp7Y5h6ip_jbhrSLd0B8z0pbCa1cJ_L7QAClOxwU4zL7bGt_8t7sPRzI0EJCwGiS9t2pXnw6KRF1SpipISeszBRcCiXPLKWZnTlTkcY4FbyUBjIgbx-XxDKBiow_Xh1fT0zX3XLpwfGbh9s6ZzSMFEQWNscDtv5IzUoCLY-BxIJyM6Dqb7FGqoWPJipQ7cDV-aEveCdkY3k7OtByM9L1mge7d6lTB68DJidH4A_HhkDFluQi3WT1iyZh2hEJMMzOetSpXt8K73wiH7bVQ
    docker:
      url: http://127.0.0.1:3200/graphql
      introspect: true
      headers:
        Authorization: Bearer eyJraWQiOiJ2aXJhc29mdCIsImFwcCI6MiwiYWxnIjoiUlMyNTYifQ.eyJpc3MiOiJWaXJhU29mdFN1cHBJc3N1ZXIiLCJpYXQiOjE3MzMyMDYzNzcsImV4cCI6MTc2NDc2MzMyOSwid2lkIjoyLCJpZHgiOiJ2aXJhc29mdCIsImp0aSI6IjcwNmQ2N2JkLWM2M2ItNGRkOC05MGNjLWIwNzlhNGFiMTQ5YyIsInNjb3BlcyI6InB1YmxpYyJ9.m9z69NuIakfk9dzYAoP_rF3-Xgj64KN0wMGkn1Dihfsx4DItIiNJlKCr2dlxh2lsLXSnuVp7Y5h6ip_jbhrSLd0B8z0pbCa1cJ_L7QAClOxwU4zL7bGt_8t7sPRzI0EJCwGiS9t2pXnw6KRF1SpipISeszBRcCiXPLKWZnTlTkcY4FbyUBjIgbx-XxDKBiow_Xh1fT0zX3XLpwfGbh9s6ZzSMFEQWNscDtv5IzUoCLY-BxIJyM6Dqb7FGqoWPJipQ7cDV-aEveCdkY3k7OtByM9L1mge7d6lTB68DJidH4A_HhkDFluQi3WT1iyZh2hEJMMzOetSpXt8K73wiH7bVQ
    prod:
      url: http://154.38.182.159:3001/graphql
      introspect: true
      headers:
        Authorization: Bearer eyJraWQiOiJ2aXJhc29mdCIsImFwcCI6MiwiYWxnIjoiUlMyNTYifQ.eyJpc3MiOiJWaXJhU29mdFN1cHBJc3N1ZXIiLCJpYXQiOjE3MzMyMDYzNzcsImV4cCI6MTc2NDc2MzMyOSwid2lkIjoyLCJpZHgiOiJ2aXJhc29mdCIsImp0aSI6IjcwNmQ2N2JkLWM2M2ItNGRkOC05MGNjLWIwNzlhNGFiMTQ5YyIsInNjb3BlcyI6InB1YmxpYyJ9.m9z69NuIakfk9dzYAoP_rF3-Xgj64KN0wMGkn1Dihfsx4DItIiNJlKCr2dlxh2lsLXSnuVp7Y5h6ip_jbhrSLd0B8z0pbCa1cJ_L7QAClOxwU4zL7bGt_8t7sPRzI0EJCwGiS9t2pXnw6KRF1SpipISeszBRcCiXPLKWZnTlTkcY4FbyUBjIgbx-XxDKBiow_Xh1fT0zX3XLpwfGbh9s6ZzSMFEQWNscDtv5IzUoCLY-BxIJyM6Dqb7FGqoWPJipQ7cDV-aEveCdkY3k7OtByM9L1mge7d6lTB68DJidH4A_HhkDFluQi3WT1iyZh2hEJMMzOetSpXt8K73wiH7bVQ
