export const STORE_KEY_CONFIG = {
  NEXT_LOCAL_STORAGE_TOKEN: 'NEXT_LOCAL_STORAGE_TOKEN',
  NEXT_USER_TOKEN: 'NEXT_USER_TOKEN',
  NEXT_CLIENT_TOKEN: 'NEXT_CLIENT_TOKEN',
  NEXT_LOCALE: 'NEXT_LOCALE',
  NEXT_THEME: 'NEXT_THEME',
};
