query headerFooter($filter: MenuFilter) {
  headerFooter(filter: $filter) {
    nodes {
      children {
        title
        children {
          title
          images
          link
        }
      }
    }
  }
}
