query headerFooter($filter: MenuFilter) {
  allMenus(filter: $filter) {
    nodes {
      children {
        title
        link
        children {
          title
          link
          images
        }
      }
    }
  }
}
