query allMenus($filter: MenuFilter) {
  currentWebsite {
    id
    menus(filter: $filter) {
      nodes {
        id
        title
        link
        images
        icon
        children {
          id
          title
          link
          images
          icon
          children {
            images
            title
            link
            icon
          }
        }
      }
    }
  }
}
