query allMenus($filter: MenuFilter) {
  allMenus(filter: $filter) {
    nodes {
      id
      title
      link
      images
      icon
      children {
        id
        title
        link
        images
        icon
        children {
          images
          title
          link
          icon
        }
      }
    }
  }
}
