query mePayments($filter: OrderFilter) {
  me {
    orders(filter: $filter) {
      nodes {
        payments {
          paymentMethod {
            preferences
          }
        }
      }
    }
  }
}
