query meOrders($filter: OrderFilter) {
  me {
    orders(filter: $filter) {
      nodes {
        id
        total
        number
        createdAt
        itemTotal
        itemCount
        websiteId
        items {
          order {
            total
          }
          variant {
            id
            price
            sku
            product {
              name
            }
            images
          }
          price
          total
          quantity
        }
        payments {
          id
          source
        }
      }
    }
  }
}
